# Automatic Differentiation


## Basic Operations

In [12]:
# 导入PyTorch库，用于张量计算和自动求导
import torch

# 创建一个包含[0.0, 1.0, 2.0, 3.0]的张量，并启用梯度跟踪
x = torch.arange(4.0, requires_grad=True)

# 计算y = 2 * (x·x)，其中torch.dot(x, x)计算x的点积（即x的平方和）
# 这是二次函数的例子：y = 2(x0² + x1² + x2² + x3²)
y = 2 * torch.dot(x, x)
print(y)


tensor(28., grad_fn=<MulBackward0>)


In [13]:
# TODO: 进行反向传播，计算x对y的梯度, 并且打印x的梯度值



# 打印x的梯度值，结果应为[0, 4, 8, 12]
# 因为对于y = 2(x0² + x1² + x2² + x3²)，每个xi的梯度为4xi
print(grad_x)
grad_x == 4 * x

tensor([ 0.,  4.,  8., 12.])


tensor([True, True, True, True])

## Gradient for Non-Scalar Variables

In [14]:
# 清零x的梯度，防止梯度累积
x.grad.zero_()

y = x * x

# 进行反向传播，计算x对y的梯度
# gradient=torch.ones(len(y))提供一个与y形状相同的梯度张量（全1向量）
# 因为y是非标量，backward()需要显式提供梯度向量
y.backward(gradient=torch.ones(len(y)))

# 打印x的当前梯度值
# 由于y = x * x，x的梯度应为2x（因为dy/dx = 2x）
# 使用全1向量作为梯度时，结果是2x * 1（即2x）
print(x.grad)

tensor([0., 2., 4., 6.])


## Detaching Computation

In [15]:
# 假设x已经是一个requires_grad=True的PyTorch张量，这里直接使用
x.grad.zero_()

# 计算y = x * x，即每个元素的平方
y = x * x

# 从计算图中分离y，创建不跟踪梯度的副本u, detach()返回一个新的张量，不再参与梯度计算
u = y.detach()

# 计算z = u * x，使用分离后的u与原始x相乘
z = u * x

# TODO: 对z的和进行反向传播，计算梯度, 并且用"=="判断x的梯度是否等于u


tensor([True, True, True, True])


# Exercise

## Exercise 1: Compute the Gradient of a Simple Scalar Function
Suppose we have a scalar function \( f(x) = 5x^2 + 3x + 2 \) and \( x \) is a tensor.

**TODO:**
- Finish the function \(f(x)\).
- Compute the gradient of \( f(x) \) with respect to \( x \) 



In [16]:
# Define a scalar function f(x) = 5x^2 + 3x + 2
x = torch.tensor([2.0], requires_grad=True)

# ----- write your answer here -----


# Print the gradient of x
print(x_grad)  # Expected output: tensor([23.])


tensor([23.])


## Exercise 2: Compute the Gradient of a Vector Function
Suppose we have  a vector function \( f(x) = x_1^2 + x_2^2 + x_3^2 \) and \( x \) is a vector.

**TODO:**
- Finish the function \(f(x)\).
- Compute the gradient of \( f(x) \) with respect to \( x \) 

In [17]:
# Define the vector variable x with 3 elements
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)


# ----- write your answer here -----


# Print the gradient of x
print(x_grad)  # Expected output: tensor([2., 4., 6.])


tensor([2., 4., 6.])
